# Versioned Properties - NeoForge

build.neoforge=21.0.158
build.neoforge_artifact=net.neoforged:neoforge

# YACL (NeoForge build), check https://modrinth.com/mod/yacl/versions?g=1.21&l=neoforge
dep.yacl=3.8.0+1.21.1-neoforge

# Embeddium (Sodium NeoForge port), check https://modrinth.com/mod/embeddium/versions?g=1.21
dep.embeddium=0.3.31+mc1.21
