# Versioned Properties - NeoForge 1.20.1
# Note: 1.20.1 uses artifact net.neoforged:forge (legacy)

build.neoforge=1.20.1-47.1.106
build.neoforge_artifact=net.neoforged:forge
build.parchment=2023.09.03

# YACL
dep.yacl=3.6.6+1.20.1-neoforge

# Embeddium (Sodium NeoForge port)
dep.embeddium=0.3.9+mc1.20.1
