# Done by Manus
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.1
maven_group=spichka.skintotem
archives_base_name=skintotem

# Dependencies
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5
fabric_version=0.116.12+1.21.1

# Loom
loom_version=1.6-SNAPSHOT
java_version=21
