pluginManagement {
	repositories {
		maven {
			name "Fabric"
			url "https://maven.fabricmc.net/"
		}
		maven {
			name "Kiku Snapshots"
			url "https://maven.kikugie.dev/snapshots"
		}
		maven {
			name "Kiku Releases"
			url "https://maven.kikugie.dev/releases"
		}
		maven {
			name "FigureStone Plugin"
			url "https://maven.darkz70.net/releases"
		}
		mavenLocal()
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id "dev.kikugie.stonecutter" version "0.9"
	id "net.darkz70.figurestone.settings" version "$figurestone_plugin_version"
}