# Versioned Properties - NeoForge

build.neoforge=21.11.0-beta
build.neoforge_artifact=net.neoforged:neoforge

# YACL (NeoForge build), check https://modrinth.com/mod/yacl/versions?g=1.21.11&l=neoforge
dep.yacl=3.8.1+1.21.11-neoforge

# Embeddium (Sodium NeoForge port), check https://modrinth.com/mod/embeddium/versions?g=1.21.11
dep.embeddium=unknown
