# Versioned Properties - NeoForge

build.neoforge=21.10.64
build.neoforge_artifact=net.neoforged:neoforge

# YACL (NeoForge build), check https://modrinth.com/mod/yacl/versions?g=1.21.10&l=neoforge
dep.yacl=3.8.0+1.21.9-neoforge

# Embeddium (Sodium NeoForge port), check https://modrinth.com/mod/embeddium/versions?g=1.21.10
dep.embeddium=unknown
