# Versioned Properties - NeoForge

build.neoforge=21.4.147
build.neoforge_artifact=net.neoforged:neoforge

# YACL (NeoForge build), check https://modrinth.com/mod/yacl/versions?g=1.21.4&l=neoforge
dep.yacl=3.8.0+1.21.4-neoforge

# Embeddium (Sodium NeoForge port), check https://modrinth.com/mod/embeddium/versions?g=1.21.4
dep.embeddium=0.3.31+mc1.21.4
