name: Debug Build

on: [workflow_dispatch]

jobs:
  debug_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDKs (17 + 21)
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            21
          distribution: 'microsoft'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew buildAndCollect+All || ./gradlew buildAndCollect || ./gradlew build
        env:
          GITHUB_ACTOR: darkz70
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: List all files (Debug)
        run: |
          echo "Listing all .jar files in the project:"
          find . -name "*.jar"
      - name: Capture ALL .jar files
        uses: actions/upload-artifact@v4
        with:
          name: All-Jars-Found
          path: "**/*.jar"
